
/* Lista de aplicativos, sus respectivos ID en AppDynamics, Los Aplicativos tienen dentro servidores con sus respectivos ID, y aplicativos vinculados con otros, 
como parent y los app como hijos. Asi como las Bases de datos con sus respectivos ID asignados en AppDynamics.
*/


  subAplicativos =[
    { parent:"NV1APP01",
      app:["ABC","APPPS","PS","FAE","FRD", "PAG","PAS","PBA","PRL","RO","SAG","MQ","IPRON","CloudSecuritySuite","PSE","NP","XXX"]
    },
 
     { parent:"CONVIVENCIAS", 
    app:[
    "BIENES APP", "ALV","AZCRIPTO","CON", "AZMAN", "BACOSI", "BDP", "BUSSINESS INTELLIGENSE", "BITLOCKER","BONOS PROTEGER", "CONTROL ASIGNACION NOTARIAL",
    "CALIDAD DE DATOS","CENSO", "COMPROMISO CLIENTES", "ENBOZADO", "FORMULARIO CONOZCA CLIENTE", "GESTION DE COBRO", "IVR AVAYA", "LIQUIDACION ADQUIRIENTE TARJETAS",
    "MONEX","BACOSI PAGOS", "PAGO AUTOMATICO SALARIOS","SIPBA BIENES ADJUDICADOS", "CONTROL ASIGNACION PERITOS", "PRON", "RIESGO", "SAGA","SAXO", "SICUVAL",
    "SISTEMA GERENCIAL TARJETAS-VISA", "MENSAJERIA SMS", "SORTEO ELECTRONICO","TARJETAS VISA", "VISOR BACOSI","BPCOBA", "CONVERSOR IBAN", "PAGARE DIGITAL","MONIBYTE"
    ,"MARCHAMOS", "EMBOZADO"]
   },
 
   { parent:"T24", app:["JBOSS-NODO2","JBOSS-ADMIN-NODO1"] }
 ]
 
    idServer=[  
 
     { parent:"Servidor Windows- Servidores Base de Datos",  
       servers: [ 
         {id: -1, name:"VP0118-NV1SQL01"}  ],
     app:[]
      },
 
     { parent:"NV1APP01", 
       servers: [ 
         {id:134 , name: "VP0118-NV1APP01"},
         {id:135 , name: "VP0200-NV1APP01"},
         {id:139 , name: "VP0118-NV1WEB01"}  
     ],
       app:["ABC","APPPS","PS","CON","FAE","FRD", "PAG","PAS","PBA","PRL","ROI","SAG","MQ","SIPRON","CloudSecuritySuite","PSE","NP","XX"]
     },
 
     { parent:"AZman",  
        servers: [ 
       {id: 208, name:"VP9999-AZMAPP01"}  ],
        app:["AZman"]
     },
 
 
     { parent:"CONVIVENCIAS", 
       servers: [
       {id: 211, name:"VP9999-S01WEB01"},
       {id: 268, name:"VP9999-S01APP01"},
       {id: 269, name:"VP9999-S01APP02"},
       {id: 270, name:"VP9999-S01WEB02"} ],
      app:[
      "EMBOZADO",
      "Banca Movil",
      "BIENES APP",
      "ALV",
      "AZCRIPTO",
      "AZMAN",
      "BACOSI",
      "BDP",
      "BUSSINESS INTELLIGENSE",
      "BITLOCKER",
      "BONOS PROTEGER",
      "CONTROL ASIGNACIÓN NOTARIAL",
      "CALIDAD DE DATOS",
      "CENSO",
      "COMPROMISO CLIENTES",
      "ENBOZADO",
      "FORMULARIO CONOZCA CLIENTE",
      "GESTION DE COBRO",
      "IVR AVAYA",
      "LIQUIDACION ADQUIRIENTE TARJETAS",
      "MONEX",
      "BACOSI PAGOS",
      "PAGO AUTOMATICO SALARIOS",
      "SIPBA BIENES ADJUDICADOS",
      "CONTROL ASIGNACIÓN PERITOS",
      "PRON",
      "RIESGO",
      "SAGA",
      "SAXO",
      "SICUVAL",
      "SISTEMA GERENCIAL TARJETAS-VISA",
      "MENSAJERIA SMS",
      "SORTEO ELECTRONICO",
      "TARJETAS VISA",
      "VISOR BACOSI",
      "BPCOBA",
      "CONVERSOR IBAN",
      "PAGARE DIGITAL",
      "MONIBYTE",
      "MARCHAMOS",
      "PUNTOS BP",
      "Ventajas Popular"
     ]
      },
 
     { parent:"T24", 
       servers: [
     {id: 250, name:"VP0118-R17WEB02"},
     {id: 235, name:"VP0118-R17WEB01"},
     {id: 246, name:"VP0200-R17WEB01"},
     {id: 247, name:"VP0200-R17WEB03"},
     {id: 248, name:"VP0200-R17WEB02"},
     {id: 261, name:"VP0118-R17WEB03"},
    ],
     app:["T24"]
     },
 
     { parent:"BANCA MOVIL", 
     servers: [
   {id: 147, name:"VP9999-SPMAPP01"},
   {id: 148, name:"VP9999-SPMAPP02"},
   {id: 119, name:"VP9999-SPMAPP03"},
   {id: 121, name:"VP9999-SPMAPP04"},
   {id: 127, name:"VP9999-SPMAPP05"}, 
   {id: 129, name:"VP9999-SPMAPP06"},
 
   {id: 244, name:"VP9999-SPMWEB01"},
   {id: 243, name:"VP9999-SPMWEB02"},
   {id: 242, name:"VP9999-SPMWEB03"},
   {id: 241, name:"VP9999-SPMWEB04"},
   {id: 240, name:"VP9999-SPMWEB05"},
   {id: 239, name:"VP9999-SPMWEB06"}],
   app:["Banca Movil"]
   },
 
   { parent:"JBOSS-CODISA", 
     servers: [
     {id: 86, name:"VP0118-JBOWEB02"}, 
     {id: 87, name:"VP0118-JBOWEB03"}],
     app:["T24"] //"JBOSS-CODISA",
 },  
 
 { parent:"JBOSS-MONTE", 
 servers: [
 {id: 224, name:"VP0200-JBOWEB02"}, 
 {id: 225, name:"VP0200-JBOWEB03"}],
 app:["T24"] //"JBOSS-MONTE",
 }, 
 
 { parent:"MARCHAMOS", 
 servers: [{id: 161, name:"VP9999-MARAPP02"}],
 app:["MARCHAMOS"]
 },
 
 
 { parent:"Pago Servicios", 
 servers: [
   {id: 262, name:"VP9999-BNAWEB05"},
   {id: 188, name:"VP9999-PSEAPP03"},
   {id: 189, name:"VP9999-PSEAPP04"},
   {id: 192, name:"VP9999-PSEWEB04"},
   {id: 194, name:"VP9999-PSEWEB06"},
   {id: 193, name:"VP9999-PSEWEB03"},
   {id: 195, name:"VP9999-PSEWEB05"},
   {id: 199, name:"VP9999-BNAWEB06"}],
 app:["Pago Servicios"]
 },  
 
 
 { parent:"Venta de Bienes", 
 servers: [
   {id: 200, name:"VP9999-APCAPP01"},
   {id: 201, name:" VP9999-APCAPP02"}],
 app:["Venta de Bienes","Ventajas Popular"]
 },
 
 { parent:"SINPE", 
 servers: [
   {id: 183, name:"VP9999-SPEWEB02"},
   {id: 184, name:"VP9999-SPEWEB01"},
   {id: 185, name:"VP9999-SPEAPP01"},
   {id: 186, name:"VP9999-SPEAPP02"},
   {id: 205, name:"VP9999-BCEWEB02"},
   {id: 207, name:"VP9999-BCEWEB01"},
   {id: 228, name:"VP0200-SALWEB01"},
   {id: 229, name:"VP0118-SALWEB01"}],
 app:["SINPE"]
 },
 
 { parent:"MAC", 
 servers: [
   {id: 298, name:"VP0200-MACWEB01"}],
 app:["MAC"]
 }
 
 ]
 
 
   idNames=[ 
     {id: 0  , name:"Dispositivo no alcanzado"},
     {id: 135, name:"ABC"},
     {id: 147, name:"ALV"},
     {id: 140, name:"APPPS"},
     {id: 155, name:"AZCRIPTO"},
     {id: 117, name:"AZMan"},
     {id: 151, name:"BACOSI"},
     {id: 145, name:"BACOSI PAGOS"},
     {id: 8,   name:"Banca Movil"},
     {id: 149, name:"BDP"},
     {id: 115, name:"BIAC"},
     {id: 172, name:"BIENES APP"},
     {id: 146, name:"BITLOCKER"},
     {id: 120, name:"BONOS PROTEGER"},
     {id: 175, name:"BPCOBA"},
     {id: 123, name:"BPS"},
     {id: 168, name:"BUSSNESS INTELLINGENSE"},
     {id: 150, name:"CALIDAD DE DATOS"},
     {id: 119, name:"CAN"},
     {id: 153, name:"CENSO"},
     {id: 139, name:"CloudSecuritySuite"},
     {id: 164, name:"COMPROMISO CLIENTES"},
     {id: 121, name:"CON"},
     {id: 157, name:"CONTROL ASIGNACION NOTARIAL"},
     {id: 166, name:"CONTROL ASIGNACION PERITOS"},
     {id: 173, name:"CONVERSOR IBAN"},
     {id: 32,  name:"CONVIVENCIAS"},
     {id: 167, name:"EMBOZADO"},
     {id: 124, name:"FAE"},
     {id: 160, name:"FORMULARIO CONOZCA CLIENTE"},
     {id: 130, name:"FRD"},
     {id: 156, name:"GESTION DE COBRO"},
     {id: 163, name:"IVR AVAYA"},
     {id: 93 , name:"JBOSS-CODISA"},
     {id: 92 , name:"JBOSS-MONTE"},
     {id: 165, name:"LIQUIDACION ADQUIRIENTE TARJETAS"},
     {id: 113, name:"MARCHAMOS"},
     {id: 144, name:"MENSAJERIA SMS"},
     {id: 171, name:"MONEX"},
     {id: 176, name:"MONIBYTE"},
     {id: 104, name:"NV1APP01"},
     {id: 128, name:"PAG"},
     {id: 174, name:"PAGARE DIGITAL"},
     {id: 161, name:"PAGO AUTOMATICO SALARIOS"},
     {id: 10,  name:"Pago Servicios"},
     {id: 122, name:"PAS"},
     {id: 127, name:"PBA"},
     {id: 125, name:"PRL"},
     {id: 126, name:"PRO"},
     {id: 142, name:"PRON"},
     {id: 136, name:"PSE"},
     {id: 112, name:"PUNTOS BP"},
     {id: 158, name:"RIESGO"},
     {id: 129, name:"SAG"},
     {id: 148, name:"SAGA"},
     {id: 159, name:"SAXO"},
     {id: 169, name:"SICUVAL"},
     {id: 162, name:"SIPBA BIENES ADJUDICADOS"},
     {id: 37,  name:"SINPE"},
     {id: 134, name:"SIPO CREDITO"},
     {id: 132, name:"SIPRON"},
     {id: 143, name:"SISTEMA GERENCIAL TARJETAS-VISA"},
     {id: 133, name:"SIV"},
     {id: 137, name:"SNP"},
     {id: 154, name:"SORTEO ELECTRONICO"},
     {id: 88,  name:"T24"},
     {id: 178, name:"T24 TEST R17"},
     {id: 170, name:"TARJETAS VISA"},
     {id: 131, name:"TMQ"},
     {id: 23,  name:"Venta de Bienes"},
     {id: 24,  name:"Ventajas Popular"},
     {id: 152, name:"VISOR BACOSI"},
     {id: 138, name:"XXX"},
     {id: 180, name:"Appdynamics"},
     {id: 167, name:"EMBOZADO"},
   ]
 
   idBD = [
     {id: 17, name:"ORACLE T24"},
     {id: 22, name:"BACOSI"}, 
     {id: 5,  name:"BANCA_Movil"}, 
     {id: 4,  name:"Bpop_Conectividad"}, 
     {id: 20, name:"MarchamosApp"}, 
     {id: 21, name:"AML_SCREENV3"}, 
     {id: 6,  name:"SAGA"}, 
     {id: 23, name:"SINPEBP"}, 
     {id: 24, name:"SIPRON"}, 
     {id: 27, name:"SIPRON"}, 
     {id: 28, name:"SIPRON"},
     {id: 29, name:"SIPRON"},
     {id: 28, name:"SIPRON"},
     {id: 28, name:"SIPRON"}   
   ]
 
   let arrayDetalleEvento =[
     "Detalle del evento",
     "Equipo de Comunicación",
     "Equipo de Seguridad",
     "Eventos",
     "Servidor T24",
     "Aplicativo T24",
     "Servidor AS400 Iseries",
     "Servidor 390 Zseries",
     "Servidor Windows- Servidores Presentación",
     "Servidor Windows- Servidores Aplicación",
     "Servidor Windows- Servidores Sucursales",
     "Servidor Windows- Servidores Reportserver",
     "Servidor Windows- Servidores Base de Datos",
     "Servidor Windows- Base de Datos",
     "Bases de datos",
     "Aplicativo Venta de Bienes",
     "Aplicativo Ventajas Popular",
     "Aplicativo SINPE",
     "Aplicativo Banca Móvil",
     "Aplicativo Pago Servicios",
     "Aplicativo CONVIVENCIAS",
     "Aplicativo SINPE MOVIL",
     "Aplicativo WEB PRESENCIAL",
     "Servidores -De Externos",
     "Aplicativo Puntos BP",
     "Aplicativo BIAC"
   ]
 
   let arrayServicioAsociado = [
     "Servicio asociado",
     "4TRESS",
     "ADMINISTRACION FILAS (SAF)",
     "ADMINISTRACION POLITICAS (GPO)",
     "ANTI MONEY LAUNDRY (AML)",
     "ANTIVIRUS",
     "APLICACIONES | CONSOLIDACION (MDW)",
     "APP BANCA MOVIL",
     "APP VENTAJAS POPULAR (AVP) Y VENTA BIENES",
     "ARQUITECTURA EMPRESARIAL (ARQ)",
     "ASSIST",
     "ASSIST CHECK VR3 (ASC) ",                                  
     "AUDITORIA | FILESHARE (AUD)",
     "AVAMAR",
     "AZMAN (AZM)",
     "BACOSI       ",                  
     "BACOSI | CREDITOS BANCARIOS (CRB)",
     "BACOSI | SINPE ELECTRONICO (SPE)",
     "BACOSI EN JAVA-",
     "BANCA FACIL",
     "BCAC (BANCREDITO)",
     "BDP",
     "BITLOCKER (BIT)",
     "BLANCO (BLN)",
     "BUS INTEGRATION SERVICE (BUS)",
     "BUSSNESS INTELLINGENSE (BIN)",                                                    
     "CAN",
     "CAR",
     "CENSO",
     "CERTIFICADOS DIGITALES",
     "CISCO",
     "Cluster BD SQL en Always On",
     "CLUSTER CONSOLIDACION",
     "COMPROMISO CLIENTES",
     "COMUNICACIONES UNIFICADAS",
     "CONSULTA IDENTIFICACION CUIDADANA",
     "CONTABILIDAD (CTB)",
     "CONTABILIDAD FILESHARED",
     "CONVIVENCIAS. BITACORA WEB (BACOSI). ENVIO DE CORREO (PINES). INDICADORES ECONOMICOS (STAND ALONE)",
     "CORREO ELECTRÓNICO",
     "DATAZEN (ZEN)",
     "DHCP (DHC)",
     "DISTRIBURED FILE SYSTEM",
     "DNS",
     "DNS SERVICE (DNS)",
     "DOMAIN CONTROLLER SERVICE",
     "DOMAIN CONTROLLER SERVICE | INET (DCI)",
     "ECO",
     "EMBOZ",
     "ENCASE COMMAND CENTER (ENC)",
     "EPO (EPO)",
     "Equipo de comunicación",
     "EXCHANGE",
     "FCC",
     "FIDEICOMISO (FID)",
     "FILE SYSTEM (FPS) ",
     "FIREWALL CHECKPOINT (CHP)",
     "FireWall Virtual",
     "GESTIO ADM",
     "GESTION COBRO",
     "GESTION IP (GIP)",
     "GESTION RIESGO | OPEN RISK (ORI)",
     "INTRANET",
     "GESTION RIESGO FINACIERO (RFI)",
     "INTRANET",
     "INTRANET DE TI",
     "INVESTOR",
     "INVESTOR (INV)",
     "INVESTOR | ADMINISTRACION CARTERA PASIVA (ACP)",                                                                                      
     "INVESTOR FIDEICOMISO ",
     "ISILON",
     "KIOSKOS (KIO)",
     "MARCHAMOS",
     "MICROSOFT ASSESSMENT PLANNING (MAP)",
     "MONITOREO (RMO)",
     "MONITOREO IPS",
     "MULTICRE (MCR)",
     "NAVEGACION Y FILTRADO DE CONTENIDO (NFC)",
     "NETSCALER",
     "No aplica",
     "OFFICE 365",
     "OFICIALIA CUMPLIMIENTO",
     "OFICIALIA CUMPLIMIENTO (OFC)",
     "OFICIALIA CUMPLIMIENTO | BASE DATOS INTERMEDIA (BDI)",                            
     "OLAP (OLP)",
     "ORACLE | VM SERVER (OVS)",
     "ORACLE VMACHINE MANAGER (OVM)",
     "PAGARE DIGITAL",
     "PAGO DE SERVICIOS",
     "PAGO SERVICIOS ELECTRONICOS (PSE)",
     "PERITOS",
     "PORTAL RH",
     "PORTAL RH (PRH) ",
     "POS",
     "PPM (PPM)",
     "PRODUCCION",
     "PROJECT SERVER 2012 (PRJ)",
     "PRON",
     "PROXY SERVER (TMG)",
     "QFLOW RECOMENDACIONES",
     "QUICK PASS (QPS)",
     "QUICKPASS",
     "REMOTE FILE SERVICE (RFS)",
     "REPORTVISION | CONTABILIDAD GENERAL",
     "RESPALDOS FILE SYSTEM (No se sabe que es)",
     "RIESGO (RIE)",
     "ROI",
     "SAS",
     "SEGURIDAD (SEC)",
     "SEGUROS | ITOP (ITO) ",
     "SERVICE MANAGER",
     "SERVICE MANAGER 2010",
     "SERVICIO PÁGINA TRANSACCIONAL",
     "SERVIDOR BASE DE DATOS SIN UTILIZAR",
     "SERVIDOR DE PRUEBAS",
     "SHAREPOINT WORKFLOW 2013 (SPW)",
     "SIAP",
     "SICA",
     "SICVECA",
     "SIPO-HIS 2006 | WIP-HIP-COM+ (HOS)",
     "SIPO-HIS 2009 | TERMINALES (HIS)",
     "SIPRE",
     "SISTEMA CENCON (SCC)",
     "SISTEMA DE SEGUROS",
     "SISTEMAS DE ACUERDOS | RECOMENDACIONES",
     "SISTEMAS DE ACUERDOS | RECOMENDACIONES JUNTA DIRECTIVA (CJD)",
     "SITIO WEB PRESENCIAL",
     "SPICEWORKS (SPI)",
     "SQL | CONSOLIDADO (FOX)",
     "SQL | CONSOLIDADO (FOX) ",
     "SQL | MANAGEMENT",
     "SQL REPORTING | CONSOLIDADO (RPS)",
     "STARH (STH)",
     "STARH-MULTISTARH     ",
     "SUITE SYSTEM CENTER ",
     "SYMANTEC",
     "SYMANTEC |  MESSAGING GATEWAY (SMG)",
     "SYSLOG SERVER",
     "SYSTEM CENTER | OPERATION MANAGER R2 (OPR)",
     "T24",
     "TASK MANAGER (TSK)",
     "TRASLADO SERVIDORES DE LA VNX EN HYPER-V",
     "VBLOCK",
     "VIRTUAL DESKTOP INFRAESTRUCTURE (VDI)",
     "VISA SIG (SGT), MONEX, CENSO, CAN, PER, CBC, PAS, GES, PAGARE DIG, SICUVAL, SORTEO ELE",                 
     "VMWARE",
     "VMWARE TEMPLATES (VVM)",
     "WEB INSPECT (WNP)",
     "WSUS (SUS)",
     "XENMOBILE (XEN)",
     "T24",
     "AUDITORIA",
         ]

         
var causasCPU = [
  "Procesos o aplicaciones que requieren una gran cantidad de recursos de CPU",
  "Programas o servicios en segundo plano que consumen recursos de la CPU",
  "Programas o procesos defectuosos con fugas de memoria o errores que consumen recursos de la CPU",
  "Sobreutilización del sistema debido a múltiples aplicaciones o procesos en ejecución",
  "Controladores de dispositivo obsoletos o defectuosos que causan un uso excesivo de la CPU",
  "Problemas de optimización del sistema operativo que resultan en un uso ineficiente de la CPU",
  "Tareas programadas o procesos automáticos que se ejecutan en momentos de alta demanda de CPU",
  "Operaciones intensivas en la CPU, como renderizado de gráficos o cálculos matemáticos complejos sobrecargan la CPU",
  "En dispositivos físicos problemas de refrigeración que hacen que la CPU funcione a temperaturas más altas y consuma más energía",
  "Falta de recursos de hardware, como memoria insuficiente",
  "Conflictos de software o incompatibilidades que generan un uso excesivo de la CPU",
  "Actualizaciones de software o descargas en segundo plano que aumentan temporalmente el uso de la CPU",
  "Procesos de indexación de archivos o búsqueda intensiva de datos",
  "Errores en el sistema operativo o en las aplicaciones que resultan en ciclos de CPU desperdiciados o bloqueos",
  "Aplicaciones con fugas de memoria o problemas de administración de memoria",
  "Configuraciones incorrectas de energía que evitan que la CPU entre en estados de bajo consumo",
  "Problemas de red, como latencia alta o transferencias de datos intensivas",
  "Incompatibilidad de software que provoca conflictos y un uso excesivo de la CPU",
  "Una aplicación de reproducción de medios defectuosa que consume recursos de la CPU incluso cuando no está en uso",
  "Un proceso de encriptación de archivos que utiliza la CPU para cifrar datos de manera segura",
  "Un programa de virtualización ejecutando múltiples máquinas virtuales y utilizando recursos de la CPU",
  "Una configuración de energía incorrecta que impide que la CPU reduzca su velocidad cuando no está bajo carga",
  "Un proceso de actualización automática de software que realiza descargas e instalaciones en segundo plano, utilizando recursos de la CPU",
  "Un programa en tiempo real que procesa flujos de información masivos, ejerciendo presión sobre la CPU",
  "Un programa que utiliza la CPU eleva el su uso generando cargas altas de CPU",
  "Un proceso que utiliza la CPU para simular hardware y ejecutar tareas de alto consumo de datos elevan el uso de la CPU",
  "Un programa que utiliza la CPU para procesar datos genera icrementos en la CPU"


];
      

let solucionesCPU = [
  "Actualizar el firmware del servidor",
  "Aumentar la cantidad de núcleos de CPU asignados",
  "Optimizar la configuración de virtualización, como VT-x o AMD-V",
  "Implementar técnicas de aprovisionamiento dinámico de recursos",
  "Reducir la cantidad de agentes y complementos de supervisión",
  "Implementar técnicas de ahorro de energía a nivel de CPU",
  "Configurar políticas de administración de recursos basadas en prioridades",
  "Realizar una segmentación de la red para separar cargas de trabajo",
  "Utilizar servicios de balanceo de carga externos",
  "Implementar una solución de gestión de contenedores",
  "Optimizar la configuración del hipervisor",
  "Reducir el uso de servicios y aplicaciones en segundo plano",
  "Implementar técnicas de aprovisionamiento de CPU basadas en demanda",
  "Utilizar herramientas de monitoreo y análisis de rendimiento",
  "Configurar políticas de programación de CPU para priorizar tareas críticas",
  "Implementar técnicas de virtualización de almacenamiento",
  "Realizar una auditoría de recursos para identificar consumidores de CPU",
  "Optimizar la gestión de tareas y procesos en el sistema operativo",
  "Implementar técnicas de deduplicación de datos",
  "Configurar políticas de limitación de CPU para usuarios y grupos",
  "Utilizar técnicas de compresión de datos en tiempo real",
  "Optimizar la configuración de la memoria virtual",
  "Implementar una solución de almacenamiento distribuido",
  "Configurar alertas y notificaciones para identificar picos de consumo",
  "Utilizar técnicas de programación asincrónica para reducir la carga de CPU",
  "Optimizar la configuración del plan de energía del servidor",

  "Optimizar el código y los algoritmos de las aplicaciones",
  "Aumentar la capacidad de CPU asignada al servidor",
  "Reducir el número de procesos en ejecución",
  "Aplicar técnicas de compresión y almacenamiento en caché",
  "Implementar una solución de equilibrio de carga",
  "Utilizar técnicas de virtualización de CPU",
  "Configurar políticas de administración de energía eficientes",
  "Establecer límites de recursos para aplicaciones y servicios",
  "Utilizar técnicas de particionamiento de CPU",
  "Optimizar el uso de recursos compartidos",
  "Configurar la afinidad de CPU para cargas de trabajo específicas",
  "Monitorear y ajustar la frecuencia de reloj de la CPU",
  "Optimizar la configuración de red y los protocolos",
  "Implementar técnicas de almacenamiento en caché a nivel de red",
  "Utilizar técnicas de precompilación o compilación anticipada",
  "Reducir la carga de procesamiento al externalizar ciertas tareas",
  "Implementar políticas de suspensión de recursos no utilizados",
  "Utilizar técnicas de limitación de velocidad de CPU",
  "Optimizar la gestión de memoria del servidor",
  "Configurar el escalado automático para adaptarse a la demanda",
  "Realizar una limpieza regular de archivos y registros innecesarios",
  "Implementar una solución de gestión de recursos",
  "Actualizar el hardware del servidor",
  "Utilizar técnicas de virtualización de red",
  "Implementar un cortafuegos para reducir el tráfico no deseado",
  "Configurar la planificación de CPU para priorizar tareas críticas",

  "Optimizar la configuración de la memoria caché",
  "Implementar técnicas de paralelización de tareas",
  "Configurar políticas de gestión de procesos",
  "Utilizar técnicas de desduplicación de código",
  "Optimizar la gestión de hilos en las aplicaciones",
  "Implementar técnicas de compresión de archivos y datos",
  "Configurar la afinidad de CPU para tareas específicas",
  "Utilizar técnicas de migración en vivo para equilibrar la carga",
  "Optimizar el uso de servicios en la nube",
  "Implementar una solución de almacenamiento en caché distribuido",
  "Configurar políticas de suspensión de servicios no esenciales",
  "Utilizar técnicas de administración de recursos basadas en políticas",
  "Optimizar la configuración del controlador de virtualización",
  "Implementar técnicas de aislamiento de recursos",
  "Configurar políticas de límites de CPU flexibles",
  "Utilizar técnicas de virtualización de almacenamiento",
  "Optimizar el uso de memoria compartida",
  "Implementar una solución de orquestación de contenedores",
  "Configurar políticas de reinicio automático para servicios críticos",
  "Utilizar técnicas de gestión de colas",
  "Optimizar el uso de instrucciones SIMD (Single Instruction, Multiple Data)",
  "Implementar técnicas de paginación eficiente",
  "Configurar políticas de programación de CPU basadas en prioridades de usuarios",
  "Utilizar técnicas de segmentación de carga de trabajo",
  "Optimizar la configuración del planificador de tareas del sistema operativo"

];

const causasBloqueoPOS = [
  'Posible Falta de conexión a Internet podria generar problemas de POS',
  'Problemas de red o enrutamiento podria generar problemas de POS',
  'Sobrecarga del sistema podria generar problemas de POS',
  'Posibles Fallas en el hardware podria generar problemas de POS',
  'Posibles Fallos en el software del POS',
  'Conflictos de software o incompatibilidades podria generar problemas de POS',
  'Problemas de alimentación eléctrica podria generar problemas de POS',
  'Configuraciones incorrectas podrian generar problemas de POS',
  'Inconsistencias en la información ingresada podrian generar problemas de POS',
  'Congestión de datos podrian generar problemas de POS',
  'Problemas de autenticación o seguridad podrian generar problemas de POS',
  'Conflictos de acceso concurrente podrian generar problemas de POS',
  'Falta de recursos de hardware suficientes podrian generar problemas de POS',
  'Problemas con dispositivos periféricos podrian generar problemas de POS',
  'Posibles Interferencias electromagnéticas podrian generar problemas de POS',
  'Posibles Errores en la comunicación entre el POS y otros sistemas',
  'Posibles Actualizaciones fallidas podrian generar problemas de POS',
  'Posibles Configuraciones de red incorrectas podrian generar problemas de POS',

  'Posible Falta de conexión a Internet podria generar problemas de POS',
  'Problemas de red o enrutamiento podria generar problemas de POS',
  'Sobrecarga del sistema podria generar problemas de POS',
  'Posibles Fallas en el hardware podria generar problemas de POS',
  'Posibles Fallos en el software del POS',
  'Conflictos de software o incompatibilidades podria generar problemas de POS',
  'Problemas de alimentación eléctrica podria generar problemas de POS',
  'Configuraciones incorrectas podrian generar problemas de POS',
  'Inconsistencias en la información ingresada podrian generar problemas de POS',
  'Congestión de datos podrian generar problemas de POS',
  'Problemas de autenticación o seguridad podrian generar problemas de POS',
  'Conflictos de acceso concurrente podrian generar problemas de POS',
  'Falta de recursos de hardware suficientes podrian generar problemas de POS',
  'Problemas con dispositivos periféricos podrian generar problemas de POS',
  'Posibles Interferencias electromagnéticas podrian generar problemas de POS',
  'Posibles Errores en la comunicación entre el POS y otros sistemas',
  'Posibles Actualizaciones fallidas podrian generar problemas de POS',
  'Posibles Configuraciones de red incorrectas podrian generar problemas de POS',
  'Fallas en la infraestructura de red podrian generar problemas de POS',
  'Errores en la configuración del sistema operativo podrian generar problemas de POS',
  'Problemas con el proveedor de servicios de Internet podrian generar problemas de POS',
  'Errores en la interpretación de datos podrian generar problemas de POS',
  'Incompatibilidad de protocolos de comunicación podria generar problemas de POS',
  'Posibles Errores en la sincronización de la base de datos podrian generar problemas de POS',
  'Problemas de seguridad con los servidores de almacenamiento de datos podrian generar problemas de POS'

];

const solucionesBloqueoPOS = [
  'Verificar la conexión a Internet',
  'Reiniciar el POS y los dispositivos de red',
  'Optimizar la carga de trabajo y los procesos del sistema',
  'Realizar mantenimiento y reparaciones del hardware',
  'Actualizar o reinstalar el software del POS',
  'Resolver conflictos de software o incompatibilidades',
  'Utilizar software antivirus y antimalware actualizado',
  'Verificar y asegurar la alimentación eléctrica',
  'Revisar y corregir las configuraciones del sistema',
  'Depurar y corregir errores de programación',
  'Mantener el software actualizado con las últimas versiones',
  'Realizar copias de seguridad y reparar la base de datos',
  'Verificar la integridad de la información ingresada',
  'Administrar y reducir la congestión de datos',
  'Comunicarse con el proveedor del servidor de pago',
  'Reforzar la autenticación y la seguridad del sistema',
  'Controlar y gestionar el acceso concurrente',
  'Mejorar los recursos de hardware según las necesidades',
  'Proporcionar capacitación y entrenamiento al personal',
  'Revisar y solucionar problemas con dispositivos periféricos',
  'Evitar interferencias electromagnéticas cercanas',
  'Verificar la comunicación entre el POS y otros sistemas',
  'Comunicarse con proveedores externos para solucionar problemas',
  'Realizar actualizaciones cuidadosamente y verificar su éxito',
  'Asegurar la configuración correcta de la red',

  'Realizar un diagnóstico de red para solucionar problemas de conexión a Internet',
  'Verificar la configuración de red y corregir cualquier problema de enrutamiento',
  'Agregar recursos de hardware adicionales para evitar la sobrecarga del sistema',
  'Reemplazar o reparar componentes de hardware defectuosos',
  'Realizar pruebas exhaustivas de software y solucionar cualquier error encontrado',
  'Actualizar o cambiar el software incompatible para asegurar la compatibilidad',
  'Implementar medidas de seguridad adicionales, como cortafuegos y sistemas de detección de intrusos',
  'Instalar sistemas de alimentación ininterrumpida (UPS) para garantizar un suministro eléctrico estable',
  'Revisar y ajustar las configuraciones del sistema según las recomendaciones del fabricante',
  'Realizar pruebas rigurosas de software y depurar cualquier error encontrado',
  'Establecer un programa de actualización y mantenimiento regular para mantener el software actualizado',
  'Implementar una estrategia de copias de seguridad automatizadas y realizar pruebas de restauración periódicas',
  'Realizar controles de integridad de datos y corregir cualquier inconsistencia detectada',
  'Optimizar el almacenamiento y la gestión de datos para reducir la congestión',
  'Mantener una comunicación constante con el proveedor del servidor de pago para resolver problemas',
  'Implementar medidas de autenticación y seguridad avanzadas, como autenticación de dos factores',
  'Implementar herramientas y políticas de acceso concurrente para evitar conflictos',
  'Actualizar los recursos de hardware para cumplir con los requisitos de rendimiento del POS',
  'Proporcionar capacitación continua al personal para mejorar la operación del POS',
  'Establecer un programa de mantenimiento regular para los dispositivos periféricos',
  'Alejar los dispositivos electrónicos que puedan causar interferencias electromagnéticas',
  'Realizar pruebas de comunicación entre el POS y otros sistemas y solucionar cualquier problema',
  'Establecer acuerdos de nivel de servicio con proveedores externos y mantener una comunicación regular',
  'Realizar pruebas exhaustivas de actualizaciones antes de implementarlas en el entorno de producción',
  'Auditar y asegurar la configuración de red, incluyendo el enrutamiento y los cortafuegos'

];


const causasCargasAltasRAM = [
  'Posible ejecución de múltiples aplicaciones simultáneamente',
  'Posible presencia de procesos o servicios consumiendo excesiva memoria RAM',
  'Posible configuración incorrecta de la asignación de memoria a las máquinas virtuales',
  'Posible uso intensivo de recursos por parte de las máquinas virtuales',
  'Posible falta de optimización en la gestión de recursos del vCenter',
  'Posible uso de aplicaciones o servicios con fugas de memoria',
  'Posibles ineficiencias en el uso de la memoria por parte de las aplicaciones o sistemas operativos',
  'Posibles errores en los controladores o firmware de los dispositivos de hardware',
  'Posible falta de ajuste de los parámetros de memoria en los sistemas operativos invitados',
  'Posible presencia de procesos en segundo plano que consumen memoria de forma excesiva',
  'Posibles problemas de fragmentación de memoria',
  'Posible uso excesivo de memoria por parte de los servidores de aplicaciones o bases de datos',
  'Posible falta de liberación de memoria después de la finalización de tareas o procesos',
  'Posibles incompatibilidades entre diferentes componentes de software',
  'Posibles problemas en la gestión de la memoria caché',
  'Posible falta de ajuste de las políticas de gestión de memoria del vCenter',
  'Posible sobredimensionamiento de las asignaciones de memoria a las máquinas virtuales',
  'Posibles fugas de memoria en los sistemas operativos invitados',
  'Posibles problemas de configuración en el clúster de servidores',
  'Posible ejecución de aplicaciones o servicios mal optimizados o con errores de programación',
  'Posibles errores en las actualizaciones de software o en los parches de seguridad',
  'Posible uso de versiones desactualizadas de software',
  'Posibles problemas de compatibilidad entre diferentes versiones de software',
  'Posible falta de monitorización y gestión proactiva de la memoria RAM',
  'Posible falta de recursos de memoria en el hardware subyacente',

  'Posible uso excesivo de memoria por parte de procesos de virtualización',
  'Posibles fugas de memoria en los hipervisores',
  'Posibles configuraciones inadecuadas de políticas de gestión de memoria en el vCenter',
  'Posibles problemas de gestión de memoria en entornos de clústeres de servidores',
  'Posible sobrecarga de máquinas virtuales con asignaciones de memoria insuficientes',
  'Posibles operaciones de copia o migración de máquinas virtuales que consumen memoria',
  'Posible uso excesivo de memoria por parte de servicios de supervisión o monitoreo',
  'Posibles errores en la planificación y asignación de recursos de memoria',
  'Posible falta de ajuste de los parámetros de memoria en los hipervisores',
  'Posibles problemas de compatibilidad entre diferentes versiones de hipervisores y vCenter',
  'Posible ejecución de aplicaciones o servicios con requisitos de memoria inadecuados',
  'Posible ejecución de tareas programadas o trabajos en segundo plano con consumo excesivo de memoria',
  'Posibles problemas en la gestión de memoria compartida entre máquinas virtuales',
  'Posibles cuellos de botella en la comunicación y transferencia de datos entre máquinas virtuales',
  'Posible falta de optimización en la gestión de memoria en entornos de alta disponibilidad',
  'Posibles errores en los controladores de dispositivos de almacenamiento que causan un uso elevado de memoria',
  'Posibles problemas en la gestión de memoria en entornos de migración en caliente (vMotion)',
  'Posible uso excesivo de memoria por parte de aplicaciones o servicios de respaldo (backup)',
  'Posibles fugas de memoria en las herramientas o agentes de administración instalados en las máquinas virtuales',
  'Posibles problemas de gestión de memoria en entornos de clústeres distribuidos',
  'Posible falta de limpieza o liberación de memoria en aplicaciones o servicios después de su uso',
  'Posible uso de aplicaciones o servicios mal optimizados que generan una alta demanda de memoria',
  'Posibles problemas de configuración de políticas de administración de memoria en los sistemas operativos invitados',
  'Posible ejecución simultánea de múltiples máquinas virtuales con altas demandas de memoria',
  'Posibles fugas de memoria en los componentes de software de virtualización',
  'Posible falta de capacidad de memoria en los servidores físicos que alojan las máquinas virtuales'
];

const solucionesCargasAltasRAM = [
  'Ajustar la asignación de memoria a las máquinas virtuales según sus necesidades',
  'Optimizar la configuración de políticas de gestión de memoria en el vCenter',
  'Monitorear y analizar el consumo de memoria de las máquinas virtuales y realizar ajustes según sea necesario',
  'Identificar y corregir fugas de memoria en los hipervisores y en las aplicaciones o servicios',
  'Implementar técnicas de compresión y deduplicación de memoria para maximizar su uso',
  'Configurar la memoria compartida entre máquinas virtuales para optimizar el uso de recursos',
  'Realizar un balanceo de carga de memoria entre los servidores físicos del clúster',
  'Implementar políticas de liberación automática de memoria para aplicaciones y servicios inactivos',
  'Utilizar herramientas de monitorización y alerta para identificar y resolver cuellos de botella de memoria',
  'Optimizar y ajustar los parámetros de gestión de memoria en los hipervisores',
  'Realizar análisis de capacidad y planificación para dimensionar adecuadamente la memoria en el vCenter',
  'Implementar técnicas de paginación y swappiness para gestionar el uso de memoria virtual',
  'Actualizar los controladores de dispositivos de hardware para resolver problemas de gestión de memoria',
  'Realizar migraciones de máquinas virtuales para equilibrar la carga de memoria entre los servidores físicos',
  'Optimizar la configuración de políticas de memoria en los sistemas operativos invitados',
  'Implementar políticas de ajuste dinámico de memoria para adaptarse a las necesidades de las aplicaciones',
  'Utilizar herramientas de análisis de rendimiento para identificar y solucionar problemas de uso de memoria',
  'Realizar ajustes en las configuraciones de memoria de las máquinas virtuales basados en patrones de uso',
  'Actualizar los hipervisores y el vCenter a versiones más recientes para corregir errores conocidos',
  'Utilizar técnicas de consolidación de máquinas virtuales para optimizar el uso de memoria',
  'Realizar pruebas de rendimiento y estrés para identificar y resolver problemas de uso excesivo de memoria',
  'Optimizar el uso de memoria en aplicaciones y servicios mediante la optimización de código y recursos',
  'Implementar políticas de limpieza y liberación de memoria en aplicaciones y servicios',
  'Realizar desfragmentación regular del almacenamiento y optimizar el uso de memoria paginada',
  'Utilizar técnicas de ajuste de memoria como overcommitment para maximizar el uso de los recursos',
  'Agregar capacidad de memoria adicional a los servidores físicos según sea necesario'
];


const causasBT = [
  "Errores de configuración de red",
  "Problemas de compatibilidad de software",
  "Cargas de trabajo desequilibradas",
  "Problemas de rendimiento en la capa de aplicación",
  "Fallas en los componentes de hardware",
  "Errores de configuración de seguridad",
  "Conflictos de recursos de almacenamiento",
  "Problemas de integración de sistemas",
  "Errores en la configuración del servidor virtual",
  "Problemas de conectividad con servicios externos",
  "Sobrecarga de solicitudes de red",
  "Problemas en la configuración de firewall",
  "Falta de capacidad de procesamiento",
  "Incompatibilidades de versiones de software",
  "Errores en la configuración de virtualización",
  "Problemas de escalado vertical insuficiente",
  "Fallas en los controladores de dispositivo",
  "Problemas de latencia de red",
  "Errores en las políticas de enrutamiento",
  "Configuraciones incorrectas de equilibrio de carga",
  "Falta de monitoreo y alertas adecuados",
  "Problemas de configuración de la red virtual",
  "Errores en la configuración de DNS",
  "Problemas de administración de energía del servidor",
  "Configuraciones incorrectas de la pila de red",
  "Fallas en los servicios de middleware",

  "Posibles problemas de configuración de red.",
  "Posibles conflictos de configuración en los servicios de red.",
  "Posible asignación insuficiente de recursos de CPU para las transacciones.",
  "Posible conexión intermitente entre los servidores virtuales y los servicios externos.",
  "Posible exceso de tráfico de red en el entorno virtualizado.",
  "Posible configuración incorrecta de la administración de energía en los servidores virtuales.",
  "Posible falta de optimización en la configuración de equilibrio de carga.",
  "Posible sobrecarga en los servidores virtuales.",
  "Posibles fallos en los componentes de almacenamiento.",
  "Posibles bloqueos de transacciones por parte de los servicios de seguridad.",
  "Posible falta de recursos de memoria para las transacciones.",
  "Posibles errores en la configuración de los servicios de aplicaciones.",
  "Posible falta de actualizaciones de software y parches.",
  "Posibles conflictos en la configuración de la red virtual.",
  "Posibles errores en la configuración de DNS.",
  "Posible falta de monitoreo y alertas adecuados.",
  "Posibles problemas de interoperabilidad entre diferentes sistemas.",
  "Posibles errores en la configuración del firewall.",
  "Posible falta de escalabilidad en los servidores virtuales.",
  "Posibles problemas en la gestión de la base de datos subyacente.",
  "Posibles errores en la configuración de la virtualización.",
  "Posibles fallos en los servicios de middleware.",
  "Posibles problemas de latencia en la red.",
  "Posible falta de capacidad de almacenamiento para las transacciones.",
  "Posibles incompatibilidades entre versiones de software.",
  "Posibles errores en las políticas de enrutamiento de red."
];


const solucionesBT = [
  "Optimizar la configuración de red",
  "Realizar ajustes de configuración de servicios de red",
  "Asignar más recursos de CPU a las transacciones",
  "Verificar y mejorar la estabilidad de la conexión con servicios externos",
  "Implementar medidas para reducir el tráfico de red",
  "Ajustar la configuración de administración de energía en los servidores virtuales",
  "Optimizar la configuración de equilibrio de carga",
  "Resolver los problemas de componentes de almacenamiento",
  "Configurar adecuadamente los servicios de seguridad para permitir las transacciones",
  "Aumentar la capacidad de memoria disponible para las transacciones",
  "Revisar y ajustar la configuración de los servicios de aplicaciones",
  "Aplicar las actualizaciones de software y parches necesarios",
  "Solucionar los conflictos en la configuración de la red virtual",
  "Realizar pruebas de interoperabilidad y resolver problemas detectados",
  "Revisar y ajustar la configuración del firewall",
  "Implementar una estrategia de escalabilidad para los servidores virtuales",
  "Corregir errores de configuración de virtualización",
  "Resolver problemas en los servicios de middleware",
  "Mejorar la latencia de red",
  "Ampliar la capacidad de almacenamiento para las transacciones",
  "Alinear las versiones de software para evitar incompatibilidades",
  "Revisar y ajustar las políticas de enrutamiento de red",

  "Optimizar la configuración de red para mejorar el rendimiento",
  "Implementar técnicas de balanceo de carga para distribuir la carga de trabajo",
  "Aumentar la capacidad de almacenamiento para manejar mayores volúmenes de datos",
  "Realizar ajustes de configuración en los servicios de aplicaciones",
  "Optimizar el uso de recursos de CPU mediante técnicas de programación eficiente",
  "Implementar soluciones de almacenamiento en caché para acelerar el acceso a datos",
  "Revisar y optimizar la configuración de la virtualización",
  "Utilizar técnicas de compresión de red para reducir el consumo de ancho de banda",
  "Implementar técnicas de escalado automático para adaptarse a la demanda",
  "Mejorar la configuración de seguridad para prevenir ataques y asegurar las transacciones",
  "Realizar pruebas de rendimiento y ajustes basados en los resultados",
  "Optimizar la configuración de la memoria virtual para un uso eficiente de los recursos",
  "Implementar soluciones de almacenamiento distribuido para mejorar la disponibilidad",
  "Utilizar técnicas de almacenamiento en caché en el lado del cliente para acelerar la carga",
  "Realizar análisis de logs y monitorización para detectar y solucionar problemas",
  "Actualizar y parchear regularmente el software y los componentes del servidor",
  "Implementar políticas de respaldo y recuperación de datos",
  "Optimizar la configuración de la red virtual para reducir la latencia",
  "Utilizar técnicas de compresión de archivos y transferencia diferencial para ahorrar ancho de banda",
  "Implementar soluciones de alta disponibilidad para minimizar el tiempo de inactividad",
  "Configurar políticas de ahorro de energía en los servidores virtuales",
  "Realizar pruebas exhaustivas de integración para garantizar la estabilidad del sistema",
  "Implementar técnicas de almacenamiento en caché de consultas para acelerar las respuestas",
  "Optimizar el uso de recursos de red mediante técnicas de QoS",
  "Utilizar soluciones de monitorización y alertas para una gestión proactiva del rendimiento",
  "Implementar técnicas de segmentación de carga para equilibrar la distribución de tareas"

];

const causasFallosSNMP = [
  "Posiblemente una configuración incorrecta de SNMP en los servidores virtuales.",
  "Posiblemente un mal funcionamiento de los agentes SNMP en los servidores virtuales.",
  "Posiblemente restricciones de firewall que bloquean el tráfico SNMP.",
  "Posiblemente problemas de conectividad de red entre el vCenter y los servidores virtuales.",
  "Posiblemente incompatibilidades entre versiones de SNMP utilizadas.",
  "Posiblemente una configuración incorrecta de comunidades SNMP.",
  "Posiblemente errores en la autenticación y autorización de SNMP.",
  "Posiblemente un número excesivo de solicitudes SNMP que sobrecargan los servidores virtuales.",
  "Posiblemente problemas de configuración en los switches de red que afectan la comunicación SNMP.",
  "Posiblemente falta de recursos de hardware para manejar las solicitudes SNMP.",
  "Posiblemente una configuración inadecuada de las trampas SNMP.",
  "Posiblemente problemas de interoperabilidad entre el vCenter y los dispositivos SNMP.",
  "Posiblemente errores en la configuración de la comunidad SNMP en el vCenter.",
  "Posiblemente problemas de compatibilidad con los controladores SNMP utilizados.",
  "Posiblemente errores en la configuración de los OID (Object Identifiers).",
  "Posiblemente problemas de latencia en la red que afectan la entrega de paquetes SNMP.",
  "Posiblemente falta de monitoreo y gestión adecuados de SNMP.",
  "Posiblemente un exceso de tráfico de red que afecta el rendimiento de SNMP.",
  "Posiblemente problemas de seguridad que impiden el acceso y el intercambio de información SNMP.",
  "Posiblemente errores en la configuración del mapeo de objetos SNMP.",
  "Posiblemente problemas de rendimiento del vCenter que afectan la recolección y el envío de datos SNMP.",
  "Posiblemente una configuración incorrecta de las sondas SNMP utilizadas.",
  "Posiblemente cambios recientes en la infraestructura de red que afectan la comunicación SNMP.",
  "Posiblemente una falta de actualización de firmware en los dispositivos SNMP.",
  "Posiblemente problemas de escalabilidad debido al crecimiento del número de dispositivos monitoreados por SNMP.",
  "Posiblemente falta de capacitación y conocimiento adecuados para administrar SNMP.",
  "Posiblemente falta de compatibilidad con versiones de SNMP en los dispositivos monitoreados.",
  "Posiblemente problemas de enrutamiento que impiden la comunicación SNMP.",
  "Posiblemente errores en la configuración de los agentes SNMP en los dispositivos.",
  "Posiblemente un mal funcionamiento del servicio SNMP en el vCenter.",
  "Posiblemente problemas de sincronización de tiempo entre el vCenter y los dispositivos SNMP.",
  "Posiblemente una configuración incorrecta de las políticas de seguridad SNMP.",
  "Posiblemente problemas de capacidad de almacenamiento para los datos SNMP recolectados.",
  "Posiblemente una falta de supervisión de los dispositivos SNMP por parte del vCenter.",
  "Posiblemente errores en la configuración de las alertas y notificaciones SNMP.",
  "Posiblemente problemas de congestión de red que afectan la entrega de paquetes SNMP.",
  "Posiblemente problemas de configuración de la tabla MIB (Management Information Base).",
  "Posiblemente una configuración incorrecta de los perfiles de acceso SNMP.",
  "Posiblemente errores en la configuración de los umbrales y límites SNMP.",
  "Posiblemente problemas de compatibilidad con las implementaciones SNMP de diferentes fabricantes.",
  "Posiblemente problemas de aislamiento de red que limitan la comunicación SNMP.",
  "Posiblemente una falta de actualización de los controladores SNMP utilizados.",
  "Posiblemente errores en la configuración de las consultas SNMP realizadas por el vCenter.",
  "Posiblemente problemas de configuración de la seguridad de la comunidad SNMP.",
  "Posiblemente falta de recursos de red para soportar el tráfico SNMP.",
  "Posiblemente problemas de congestión en el vCenter debido a una alta carga de trabajo SNMP.",
  "Posiblemente errores en la interpretación y procesamiento de los datos SNMP recibidos.",
  "Posiblemente una configuración incorrecta del acceso remoto SNMP en los dispositivos.",
  "Posiblemente problemas de configuración del agente SNMP en el vCenter.",
  "Posiblemente restricciones de acceso a la red que impiden la comunicación SNMP.",
  "Posiblemente problemas de compatibilidad con las versiones del protocolo SNMP utilizadas.",
  "Posiblemente errores en la configuración de las notificaciones de trampas SNMP."
];

const solucionesFallosSNMP = [
  "Posiblemente se requiera reiniciar los agentes SNMP en los dispositivos afectados.",
  "Posiblemente sea necesario verificar y corregir la configuración de red para permitir el tráfico SNMP.",
  "Posiblemente deban actualizarse los controladores SNMP en los dispositivos monitoreados.",
  "Posiblemente sea necesario revisar y ajustar la configuración de los perfiles de acceso SNMP.",
  "Posiblemente se deba verificar y corregir la configuración de las políticas de seguridad SNMP.",
  "Posiblemente sea necesario aumentar la capacidad de almacenamiento para los datos SNMP recolectados.",
  "Posiblemente sea necesario realizar un análisis exhaustivo de las consultas SNMP realizadas por el vCenter.",
  "Posiblemente se requiera ajustar los umbrales y límites SNMP para adecuarlos a las necesidades.",
  "Posiblemente se deba revisar y corregir la configuración de las alertas y notificaciones SNMP.",
  "Posiblemente sea necesario revisar y actualizar las versiones del protocolo SNMP utilizadas.",
  "Posiblemente se deba verificar y corregir la configuración de las comunidades SNMP utilizadas.",
  "Posiblemente sea necesario optimizar el uso de recursos de red para soportar el tráfico SNMP.",
  "Posiblemente se requiera realizar una revisión exhaustiva de la configuración de las trampas SNMP.",
  "Posiblemente se deban realizar pruebas de compatibilidad con las implementaciones SNMP de diferentes fabricantes.",
  "Posiblemente sea necesario implementar mecanismos de monitoreo y gestión más robustos para SNMP.",
  "Posiblemente se deba revisar y ajustar la configuración de las consultas SNMP para mejorar la eficiencia.",
  "Posiblemente se requiera revisar y corregir la configuración de la seguridad de la comunidad SNMP.",
  "Posiblemente sea necesario optimizar la configuración del enrutamiento para mejorar la comunicación SNMP.",
  "Posiblemente se deba realizar una revisión exhaustiva de la configuración de las tablas MIB.",
  "Posiblemente sea necesario implementar soluciones de balanceo de carga para gestionar el tráfico SNMP.",
  "Posiblemente se requiera implementar soluciones de compresión de datos para reducir la carga de la red SNMP.",
  "Posiblemente se deba revisar y ajustar la configuración de las consultas SNMP para reducir la carga de los dispositivos.",
  "Posiblemente se requiera mejorar la infraestructura de red para reducir la latencia y mejorar la entrega de paquetes SNMP.",
  "Posiblemente se deba realizar una actualización del firmware en los dispositivos SNMP para corregir posibles problemas.",
  "Posiblemente se requiera capacitar al personal responsable del monitoreo y gestión de SNMP para mejorar la eficacia.",
  "Posiblemente se deba implementar soluciones de respaldo y recuperación para proteger los datos y configuraciones SNMP.",
  "Posiblemente se deba realizar una limpieza y optimización de la base de datos SNMP.",
  "Posiblemente se requiera implementar soluciones de monitoreo proactivo para detectar fallos en tiempo real.",
  "Posiblemente sea necesario realizar pruebas de rendimiento y ajustar la configuración de los dispositivos SNMP.",
  "Posiblemente se deba revisar y corregir la configuración de las sondas SNMP utilizadas.",
  "Posiblemente se requiera implementar soluciones de detección y mitigación de ataques SNMP.",
  "Posiblemente sea necesario realizar una revisión exhaustiva de los permisos de acceso SNMP en los dispositivos.",
  "Posiblemente se deba revisar y ajustar la configuración del acceso remoto SNMP en los dispositivos.",
  "Posiblemente se requiera implementar soluciones de encriptación para proteger las comunicaciones SNMP.",
  "Posiblemente se deba realizar una auditoría de seguridad de SNMP para identificar posibles vulnerabilidades.",
  "Posiblemente se requiera implementar soluciones de redundancia y alta disponibilidad para garantizar la continuidad de SNMP.",
  "Posiblemente sea necesario revisar y actualizar las versiones de firmware en los dispositivos SNMP.",
  "Posiblemente se deba realizar un análisis de la topología de red para identificar posibles cuellos de botella SNMP.",
  "Posiblemente se requiera implementar soluciones de segmentación de red para mejorar la seguridad y el rendimiento de SNMP.",
  "Posiblemente se deba revisar y ajustar la configuración de los objetos SNMP monitoreados para reducir la carga.",
  "Posiblemente se requiera implementar soluciones de detección y resolución automática de problemas en SNMP.",
  "Posiblemente sea necesario realizar pruebas de interoperabilidad con otros sistemas y dispositivos SNMP.",
  "Posiblemente se deba revisar y corregir la configuración del mapeo de objetos SNMP en los dispositivos.",
  "Posiblemente se requiera implementar soluciones de segmentación de red para mejorar la eficiencia de SNMP.",
  "Posiblemente se deba realizar una revisión exhaustiva de los registros y eventos SNMP para identificar problemas recurrentes.",
  "Posiblemente se requiera implementar soluciones de gestión de versiones para controlar los cambios en la configuración SNMP.",
  "Posiblemente sea necesario implementar soluciones de aislamiento de red para proteger SNMP de posibles ataques.",
  "Posiblemente se deba revisar y ajustar la configuración de las consultas programadas y periódicas de SNMP.",
  "Posiblemente se requiera implementar soluciones de respaldo y recuperación para garantizar la integridad de los datos SNMP.",
  "Posiblemente sea necesario realizar una revisión exhaustiva de las políticas de seguridad y cumplimiento aplicadas a SNMP.",
  "Posiblemente se deba revisar y corregir la configuración del tiempo de retención de datos SNMP."
]

const causasFallosBDInaccesible = [
  "Posiblemente fallo de conectividad de red.",
  "Posiblemente error en la configuración de puertos de red.",
  "Posiblemente sobrecarga de recursos del servidor de base de datos.",
  "Posiblemente falta de espacio en disco.",
  "Posiblemente error en servicios o procesos de la base de datos.",
  "Posiblemente problema de autenticación o credenciales incorrectas.",
  "Posiblemente base de datos en estado de mantenimiento o actualización.",
  "Posiblemente fallo en dispositivos de almacenamiento asociados.",
  "Posiblemente alto consumo de recursos en vCenter o servidores virtuales.",
  "Posiblemente error en configuración de infraestructura de red.",
  "Posiblemente error interno en la base de datos.",
  "Posiblemente exceso de conexiones concurrentes.",
  "Posiblemente error en configuración de políticas de seguridad.",
  "Posiblemente problema de permisos de usuario.",
  "Posiblemente error en controladores o drivers de la base de datos.",
  "Posiblemente conflicto de versiones entre vCenter, servidores virtuales y base de datos.",
  "Posiblemente error en configuración de conectividad SSL/TLS.",
  "Posiblemente falta de recursos de memoria o CPU.",
  "Posiblemente error en configuración de direcciones IP o nombres de host.",
  "Posiblemente sobrecarga en vCenter o servidores virtuales."
];

const solucionesFallosBDInaccesible = [
  "Verificar conectividad de red.",
  "Corregir configuración de puertos de red.",
  "Optimizar recursos del servidor de base de datos.",
  "Liberar espacio en disco.",
  "Solucionar errores en servicios o procesos.",
  "Verificar autenticación o credenciales.",
  "Esperar finalización de mantenimiento o actualización.",
  "Resolver fallos en dispositivos de almacenamiento.",
  "Optimizar consumo de recursos en vCenter o servidores virtuales.",
  "Corregir configuración de infraestructura de red.",
  "Solucionar errores internos de la base de datos.",
  "Administrar conexiones concurrentes.",
  "Ajustar políticas de seguridad.",
  "Revisar y corregir permisos de usuario.",
  "Actualizar controladores o drivers de la base de datos.",
  "Resolver conflictos de versiones.",
  "Corregir configuración de conectividad SSL/TLS.",
  "Aumentar recursos de memoria o CPU.",
  "Verificar configuración de direcciones IP o nombres de host.",
  "Aliviar sobrecarga en vCenter o servidores virtuales."
];


const causasAlertasAlmacenamiento = [
  "Límite de capacidad alcanzado.",
  "Archivos de registro grandes.",
  "Archivos temporales acumulados.",
  "Datos duplicados.",
  "Retención de datos incorrecta.",
  "Copias de seguridad frecuentes.",
  "Snapshots en exceso.",
  "Fragmentación de almacenamiento.",
  "Compresión de datos ineficiente.",
  "Uso excesivo de archivos multimedia.",
  "Mala gestión de versiones de archivos.",
  "Crecimiento no planificado de datos.",
  "Eliminación inadecuada de archivos.",
  "Archivos corruptos.",
  "Escasez de espacios de almacenamiento.",
  "Reservas de espacio ineficientes.",
  "Inconsistencia en la asignación de recursos.",
  "Problemas de replicación de datos.",
  "Falta de compresión de archivos.",
  "Errores en la compresión de archivos.",
  "Mala gestión de archivos de registro.",
  "Falta de limpieza de archivos obsoletos.",
  "Archivos temporales no eliminados correctamente.",
  "Errores en la compresión de imágenes.",
  "Crecimiento descontrolado de bases de datos."
];

const solucionesAlertasAlmacenamiento = [
  "Posiblemente se requiera aumentar la capacidad de almacenamiento.",
  "Posiblemente se deban gestionar y reducir archivos de registro.",
  "Posiblemente se deban eliminar archivos temporales o de caché.",
  "Posiblemente se deba optimizar y eliminar datos duplicados.",
  "Posiblemente se deba ajustar y revisar políticas de retención de datos.",
  "Posiblemente se deban reducir las copias de seguridad frecuentes.",
  "Posiblemente se deba reducir la creación de snapshots.",
  "Posiblemente se deba desfragmentar el almacenamiento.",
  "Posiblemente se deba mejorar la compresión de datos.",
  "Posiblemente se deba limitar el uso de archivos multimedia.",
  "Posiblemente se deba gestionar mejor las versiones de archivos.",
  "Posiblemente se deba planificar el crecimiento de datos.",
  "Posiblemente se deban eliminar archivos de forma adecuada.",
  "Posiblemente se deban corregir archivos corruptos.",
  "Posiblemente se deba ampliar el espacio de almacenamiento.",
  "Posiblemente se deba optimizar las reservas de espacio.",
  "Posiblemente se deba revisar la asignación de recursos.",
  "Posiblemente se deba solucionar problemas de replicación de datos.",
  "Posiblemente se deba mejorar la compresión de archivos.",
  "Posiblemente se deba corregir errores en la compresión de archivos.",
  "Posiblemente se deba gestionar mejor los archivos de registro.",
  "Posiblemente se deban eliminar archivos obsoletos.",
  "Posiblemente se deban eliminar archivos temporales de forma adecuada.",
  "Posiblemente se deban corregir errores en la compresión de imágenes.",
  "Posiblemente se deba controlar el crecimiento de bases de datos."
];

const causasProblemasDisponibilidad = [
  "Podría haberse producido una falla en la conectividad de red.",
  "Podría haberse detectado una configuración incorrecta de la infraestructura de red.",
  "Podría haberse experimentado una sobrecarga de recursos en el vCenter o servidores virtuales.",
  "Podrían haberse presentado errores en los servicios o procesos del vCenter o servidores virtuales.",
  "Podría no haberse contado con redundancia adecuada en la infraestructura.",
  "Podrían haberse registrado fallos en los sistemas de alimentación eléctrica.",
  "Podrían haberse presentado problemas en los sistemas de enfriamiento.",
  "Podría haberse configurado incorrectamente el balanceo de carga.",
  "Podría haberse producido una incompatibilidad entre versiones de software.",
  "Podrían haberse presentado problemas en los sistemas de almacenamiento.",
  "Podría haberse configurado incorrectamente el respaldo y recuperación.",
  "Podría no haberse contado con una escalabilidad suficiente en la infraestructura.",
  "Podría haberse configurado incorrectamente las políticas de alta disponibilidad.",
  "Podría haberse producido un fallo en los sistemas de virtualización.",
  "Podría haberse gestionado inadecuadamente los recursos.",
  "Podrían haberse presentado errores en la configuración de seguridad.",
  "Podría haberse carecido de un monitoreo y alertas adecuados.",
  "Podrían haberse presentado deficiencias en los sistemas de gestión de incidencias.",
  "Podrían haberse presentado problemas en los sistemas de gestión de cambios.",
  "Podría haberse configurado incorrectamente el DNS o la resolución de nombres.",
  "Podría no haberse implementado políticas de tolerancia a fallos.",
  "Podría haberse producido una incompatibilidad entre componentes de hardware.",
  "Podrían haberse presentado errores en la configuración de la virtualización de red.",
  "Podría haberse producido una falla en los sistemas de detección y prevención de intrusiones.",
];

const solucionesProblemasDisponibilidad = [
  "Podría solucionarse restableciendo la conectividad de red.",
  "Podría corregirse configurando adecuadamente la infraestructura de red.",
  "Podría aliviarse la sobrecarga de recursos optimizando el vCenter o servidores virtuales.",
  "Podrían corregirse los errores en los servicios o procesos del vCenter o servidores virtuales.",
  "Podría implementarse redundancia adecuada en la infraestructura.",
  "Podrían solucionarse los fallos en los sistemas de alimentación eléctrica.",
  "Podrían resolverse los problemas en los sistemas de enfriamiento.",
  "Podría ajustarse la configuración del balanceo de carga.",
  "Podría solucionarse mediante actualización o corrección de las versiones de software.",
  "Podrían resolverse los problemas en los sistemas de almacenamiento.",
  "Podría configurarse correctamente el respaldo y recuperación.",
  "Podría escalarse la infraestructura para cubrir las demandas.",
  "Podría ajustarse la configuración de políticas de alta disponibilidad.",
  "Podría solucionarse mediante actualización o corrección de los sistemas de virtualización.",
  "Podría optimizarse la gestión de recursos.",
  "Podrían corregirse los errores en la configuración de seguridad.",
  "Podría implementarse un sistema de monitoreo y alertas adecuado.",
  "Podrían mejorarse los sistemas de gestión de incidencias.",
  "Podrían optimizarse los sistemas de gestión de cambios.",
  "Podría ajustarse la configuración de DNS o resolución de nombres.",
  "Podría implementarse un plan de recuperación ante desastres.",
  "Podrían implementarse políticas de tolerancia a fallos.",
  "Podría solucionarse mediante actualización o corrección de componentes de hardware.",
  "Podrían corregirse los errores en la configuración de la virtualización de red.",
  "Podría mejorarse la detección y prevención de intrusiones.",
  "Podrían optimizarse los sistemas de monitoreo de rendimiento."
];

const causasProblemasHTTP = [
  "Podría haberse producido un error en la configuración del servidor web.",
  "Podría haberse generado una mala interpretación de las cabeceras HTTP.",
  "Podría haberse producido una congestión en la red.",
  "Podría haberse producido un problema con los certificados SSL/TLS.",
  "Podrían haberse presentado errores en el enrutamiento de las solicitudes HTTP.",
  "Podrían haberse configurado incorrectamente las reglas de firewall.",
  "Podría haberse generado un error en la configuración del balanceador de carga.",
  "Podrían haberse presentado problemas de compatibilidad entre el cliente y el servidor.",
  "Podría haberse producido una denegación de servicio (DoS) o ataque de inundación.",
  "Podría haberse producido un error en la implementación del protocolo HTTP.",
  "Podría haberse agotado el límite de conexiones simultáneas.",
  "Podría haberse producido un error en la configuración del caché HTTP.",
  "Podría haberse generado un error en la gestión de sesiones HTTP.",
  "Podría haberse producido un problema con el almacenamiento en caché del navegador.",
  "Podría haberse generado un error en la interpretación de los códigos de estado HTTP.",
  "Podrían haberse presentado problemas de latencia en la red.",
  "Podría haberse producido un error en la codificación de caracteres en las respuestas HTTP.",
  "Podría haberse generado un error en la autenticación o autorización de las solicitudes.",
  "Podrían haberse presentado problemas con la resolución de nombres de dominio.",
  "Podría haberse producido un problema con los encabezados de seguridad HTTP (HTTP headers).",
  "Podrían haberse presentado problemas con la gestión de cookies.",
  "Podría haberse generado un error en la compresión de las respuestas HTTP.",
  "Podría haberse producido un error en la interpretación del contenido de las solicitudes o respuestas.",
  "Podrían haberse presentado problemas con los métodos o verbos HTTP utilizados.",
  "Podría haberse producido un error en la configuración del proxy HTTP.",
  "Podría haberse generado un error en la gestión de redirecciones HTTP."
];

const solucionesProblemasHTTP = [
  "Verificar configuración del servidor web.",
  "Revisar interpretación de cabeceras HTTP.",
  "Resolver congestión en la red.",
  "Corregir problemas de certificados SSL/TLS.",
  "Revisar enrutamiento de solicitudes HTTP.",
  "Ajustar reglas de firewall.",
  "Verificar configuración del balanceador de carga.",
  "Solucionar problemas de compatibilidad.",
  "Mitigar ataques DoS o de inundación.",
  "Revisar implementación del protocolo HTTP.",
  "Aumentar límite de conexiones simultáneas.",
  "Optimizar configuración del caché HTTP.",
  "Solucionar problemas de gestión de sesiones.",
  "Limpiar almacenamiento en caché del navegador.",
  "Corregir interpretación de códigos de estado HTTP.",
  "Resolver problemas de latencia en la red.",
  "Ajustar codificación de caracteres en respuestas HTTP.",
  "Revisar autenticación y autorización de solicitudes.",
  "Solucionar problemas de resolución de nombres de dominio.",
  "Verificar configuración de encabezados de seguridad HTTP.",
  "Resolver problemas con gestión de cookies.",
  "Corregir compresión de respuestas HTTP.",
  "Revisar interpretación de contenido de solicitudes o respuestas.",
  "Asegurar correctos métodos o verbos HTTP utilizados.",
  "Verificar configuración del proxy HTTP.",
  "Solucionar problemas de redirecciones HTTP."
];

const causasIndisponibilidadAgente = [
  "Podría haberse producido un fallo en la conexión de red.",
  "Podría haberse configurado incorrectamente el agente.",
  "Podrían haberse agotado los recursos en la máquina.",
  "Podría haberse generado un error en el registro del agente.",
  "Podrían haberse presentado problemas con los permisos de acceso.",
  "Podría haberse producido un conflicto con otros componentes del sistema.",
  "Podría haberse generado un error en el controlador de AppDynamics.",
  "Podría haberse producido un error en la autenticación del agente.",
  "Podría haberse presentado un problema en la comunicación TLS/SSL.",
  "Podría haberse producido una incompatibilidad de versiones.",
  "Podría haberse producido un fallo en la detección del proceso del agente.",
  "Podrían haberse configurado incorrectamente el firewall o las reglas de seguridad.",
  "Podría haberse generado un error en la configuración del certificado.",
  "Podría haberse producido un error en el proceso de inicio del agente.",
  "Podría haberse omitido la aplicación de actualizaciones o parches.",
  "Podría haberse generado un error en la gestión de credenciales.",
  "Podrían haberse presentado problemas con la infraestructura de red.",
  "Podría haberse producido una inconsistencia en la configuración del agente.",
  "Podrían haberse presentado problemas en la resolución de DNS.",
  "Podría haberse producido un fallo en la sincronización de tiempos.",
  "Podría haberse generado un problema con la política de seguridad.",
  "Podría haberse agotado el espacio de almacenamiento disponible.",
  "Podría haberse producido un error en la configuración de la monitorización.",
  "Podría haberse generado un problema en la instalación del agente.",
  "Podría haberse producido un fallo en la autenticación del controlador.",
  "Podrían haberse presentado problemas con la carga del agente en la máquina.",
  "Podría haberse producido un problema en el servicio de registro del agente.",
  "Podría haberse generado un error en la conexión al controlador de AppDynamics.",
  "Podrían haberse presentado fallos en la validación de certificados de confianza.",
  "Podría haberse generado un problema con el sistema operativo de la máquina.",
  "Podría haberse producido una incompatibilidad con el entorno de virtualización.",
  "Podría haberse configurado incorrectamente la cuenta de servicio.",
  "Podrían haberse presentado problemas con la configuración de enrutamiento de red.",
  "Podría haberse generado un fallo en la resolución de nombres de dominio.",
  "Podría haberse presentado un problema con el cifrado de comunicaciones.",
  "Podría haberse configurado incorrectamente el proxy de red.",
  "Podría haberse generado un problema con el plan de direccionamiento IP.",
  "Podría haberse producido un fallo en la detección de cambios de configuración.",
  "Podrían haberse presentado problemas con las políticas de cortafuegos.",
  "Podría haberse generado un error en la configuración del agente de AppDynamics.",
  "Podría haberse producido un fallo en la sincronización de la hora del sistema.",
  "Podría haberse configurado incorrectamente la ruta de acceso al agente.",
  "Podría haberse presentado un problema con los certificados de confianza.",
  "Podría haberse generado un error en la comunicación entre el agente y el controlador.",
  "Podrían haberse presentado problemas con los permisos de ejecución del agente.",
  "Podría haberse producido un fallo en el registro de eventos del agente.",
  "Podría haberse generado un problema con la configuración de los recursos del agente.",
  "Podría haberse presentado una incompatibilidad con las bibliotecas del sistema.",
  "Podría haberse producido un fallo en la inicialización del agente.",
  "Podría haberse configurado incorrectamente la autenticación del agente.",
  "Podría haberse generado un error en la configuración de la comunicación segura.",
  "Podrían haberse presentado problemas con la conectividad de red del agente."

];

const solucionesIndisponibilidadAgente = [
  "Podría solucionarse reiniciando el agente.",
  "Podría resolverse reinstalando el agente.",
  "Podría corregirse actualizando la versión del agente.",
  "Podría solucionarse verificando la configuración de red del agente.",
  "Podría resolverse verificando los permisos de acceso del agente.",
  "Podría corregirse reiniciando el controlador de AppDynamics.",
  "Podría solucionarse reconfigurando la autenticación del agente.",
  "Podría resolverse generando un nuevo certificado para el agente.",
  "Podría corregirse verificando la conectividad de red entre el agente y el controlador.",
  "Podría solucionarse revisando y actualizando las reglas de firewall.",
  "Podría resolverse verificando la disponibilidad de recursos en la máquina.",
  "Podría corregirse ajustando la configuración de TLS/SSL del agente.",
  "Podría solucionarse verificando la compatibilidad de versiones entre el agente y el controlador.",
  "Podría resolverse solucionando posibles conflictos de IP o puertos.",
  "Podría corregirse verificando la correcta instalación y configuración del agente.",
  "Podría solucionarse actualizando el sistema operativo de la máquina.",
  "Podría resolverse optimizando el rendimiento de la infraestructura de red.",
  "Podría corregirse generando nuevos certificados de confianza.",
  "Podría solucionarse ajustando la configuración de resolución de DNS.",
  "Podría resolverse verificando y corrigiendo errores de configuración del agente.",
  "Podría corregirse generando nuevos tokens de autenticación para el agente.",
  "Podría solucionarse realizando un diagnóstico de conectividad de red.",
  "Podría resolverse verificando la correcta sincronización de tiempo entre el agente y el controlador.",
  "Podría corregirse ajustando la configuración de recursos del agente.",
  "Podría solucionarse generando informes de errores y buscando soluciones conocidas.",
  "Podría resolverse verificando la compatibilidad del agente con la plataforma de virtualización.",
  "Podría solucionarse verificando la conectividad de red entre el agente y el controlador.",
  "Podría resolverse revisando los logs del agente en busca de errores.",
  "Podría corregirse verificando y actualizando la configuración de seguridad del agente.",
  "Podría solucionarse reiniciando el servicio de AppDynamics en la máquina.",
  "Podría resolverse ajustando la configuración de recursos asignados al agente.",
  "Podría corregirse reinstalando el controlador de AppDynamics.",
  "Podría solucionarse generando nuevos certificados de confianza para el agente.",
  "Podría resolverse verificando y actualizando la versión del controlador de AppDynamics.",
  "Podría corregirse solucionando problemas de conectividad de red en el entorno virtualizado.",
  "Podría solucionarse ajustando la configuración del cortafuegos o reglas de seguridad.",
  "Podría resolverse verificando la disponibilidad y acceso a los recursos de red necesarios.",
  "Podría corregirse generando una nueva clave de API para el agente.",
  "Podría solucionarse realizando una comprobación de integridad del agente.",
  "Podría resolverse reiniciando el servicio del agente en la máquina.",
  "Podría corregirse verificando y actualizando la configuración de tiempo y sincronización.",
  "Podría solucionarse ajustando la configuración de enrutamiento de red.",
  "Podría resolverse generando nuevos certificados de autenticación para el agente.",
  "Podría corregirse verificando y actualizando la configuración de almacenamiento del agente.",
  "Podría solucionarse realizando una reinstalación limpia del agente.",
  "Podría resolverse verificando y ajustando los permisos de archivo y carpeta del agente.",
  "Podría corregirse solucionando problemas de compatibilidad entre el agente y el sistema operativo.",
  "Podría solucionarse verificando y actualizando la configuración de proxy del agente.",
  "Podría resolverse ajustando la configuración de red del agente.",
  "Podría corregirse generando un nuevo token de acceso para el agente.",
  "Podría solucionarse verificando y actualizando la configuración de cifrado del agente.",
  "Podría resolverse ajustando la configuración de límites de recursos del agente."

];

const causasBrokenPipe = [
  "Podría ser causado por una pérdida temporal de conectividad de red.",
  "Podría ser causado por una interrupción en el flujo de datos entre dos componentes.",
  "Podría ser causado por una configuración incorrecta de los protocolos de comunicación.",
  "Podría ser causado por una falla en el control de errores y retransmisiones.",
  "Podría ser causado por un tiempo de espera agotado en la comunicación.",
  "Podría ser causado por un conflicto de direccionamiento IP.",
  "Podría ser causado por una incompatibilidad de versiones de los componentes.",
  "Podría ser causado por un cierre abrupto de la conexión por parte de uno de los extremos.",
  "Podría ser causado por una saturación o sobrecarga en el sistema.",
  "Podría ser causado por un mal funcionamiento en los dispositivos de red.",
  "Podría ser causado por una interferencia o ruido en la señal de comunicación.",
  "Podría ser causado por una restricción de firewall o reglas de seguridad.",
  "Podría ser causado por un error en la negociación de parámetros de comunicación.",
  "Podría ser causado por una interferencia electromagnética.",
  "Podría ser causado por una pérdida de conexión debido a la migración de una máquina virtual.",
  "Podría ser causado por una caída del servicio de red o del proveedor de servicios.",
  "Podría ser causado por una interferencia en el enlace físico de la red.",
  "Podría ser causado por una interrupción en la energía eléctrica del equipo de red.",
  "Podría ser causado por un error en la codificación o decodificación de los datos transmitidos.",
  "Podría ser causado por una congestión en la red debido al alto tráfico de datos.",
  "Podría ser causado por una interferencia en la transmisión de datos causada por dispositivos cercanos.",
  "Podría ser causado por una inestabilidad en la conexión inalámbrica.",
  "Podría ser causado por una falla en el hardware de red.",
  "Podría ser causado por un problema en el sistema operativo o software de red.",
  "Podría ser causado por una interrupción en la conexión causada por eventos externos, como desastres naturales.",
  "Podría ser causado por una configuración incorrecta de los parámetros de red en los dispositivos involucrados."
];

const solucionesBrokenPipe = [
  "Podría solucionarse restableciendo la conexión y reintentando la comunicación.",
  "Podría resolverse ajustando los tiempos de espera y los mecanismos de retransmisión.",
  "Podría corregirse verificando y restableciendo la configuración de red de los componentes involucrados.",
  "Podría solucionarse optimizando el rendimiento y capacidad de los dispositivos de red.",
  "Podría resolverse implementando redundancia y balanceo de carga en la infraestructura de red.",
  "Podría corregirse actualizando los controladores y firmware de los dispositivos de red.",
  "Podría solucionarse realizando pruebas de conectividad y diagnóstico de problemas en la red.",
  "Podría resolverse mejorando la calidad y estabilidad de la señal de comunicación.",
  "Podría corregirse optimizando la configuración de los firewalls y reglas de seguridad.",
  "Podría solucionarse implementando mecanismos de detección y recuperación automática de conexiones.",
  "Podría resolverse monitoreando y administrando adecuadamente los recursos de red.",
  "Podría corregirse implementando políticas de gestión de tráfico y priorización de servicios.",
  "Podría solucionarse identificando y solucionando problemas de interferencia electromagnética.",
  "Podría resolverse realizando un análisis de rendimiento y ajuste de los parámetros de comunicación.",
  "Podría corregirse actualizando y parcheando los sistemas operativos y software de red.",
  "Podría solucionarse implementando medidas de seguridad adicionales para prevenir ataques o intrusiones.",
  "Podría resolverse optimizando la infraestructura de red para garantizar una mayor capacidad de procesamiento.",
  "Podría corregirse reconfigurando los dispositivos de red para eliminar posibles conflictos de direccionamiento.",
  "Podría solucionarse mejorando la gestión y supervisión de los enlaces físicos de la red.",
  "Podría resolverse implementando un sistema de respaldo y recuperación ante fallas de red.",
  "Podría corregirse implementando soluciones de mejora de la calidad de servicio (QoS) para priorizar el tráfico crítico.",
  "Podría solucionarse realizando una revisión exhaustiva de la topología de red y su diseño.",
  "Podría resolverse implementando técnicas de compresión y optimización de datos para reducir el volumen de la comunicación.",
  "Podría corregirse estableciendo acuerdos de nivel de servicio (SLA) y mecanismos de penalización por interrupciones.",
  "Podría solucionarse realizando pruebas de carga y rendimiento para identificar cuellos de botella en la red.",
  "Podría resolverse implementando mecanismos de detección y prevención de congestión de red.",
  "Podría corregirse implementando una arquitectura de red distribuida para reducir la dependencia de un único punto de fallo."
];

const causasCLRGarbage = [
  "Mala gestión de memoria en la aplicación.",
  "Bucle infinito o recursión excesiva en el código.",
  "Objetos grandes o fugas de memoria en el programa.",
  "Ineficiencia en la recolección de basura.",
  "Falta de optimización en el código de la aplicación.",
  "Uso intensivo de recursos en el proceso de recolección de basura.",
  "Referencias fuertes a objetos innecesarios.",
  "Dependencia de objetos estáticos o de larga duración.",
  "Uso inadecuado de estructuras de datos.",
  "Múltiples hilos de ejecución compitiendo por recursos de memoria.",
  "Falta de liberación de recursos no administrados.",
  "Exceso de objetos temporales o intermedios.",
  "Deficiencias en el algoritmo de recolección de basura.",
  "Implementación incorrecta o falta de finalizadores de objetos.",
  "Uso inadecuado de pines de memoria.",
  "Falta de liberación de conexiones a recursos externos.",
  "Interferencia de extensiones o complementos de terceros.",
  "Uso excesivo de eventos o suscripciones.",
  "Falta de compactación de la memoria.",
  "Falta de monitoreo y ajuste del recolector de basura.",
  "Errores en la gestión de punteros y referencias.",
  "Fragmentación de memoria en el sistema.",
  "Falta de administración adecuada de la memoria en bibliotecas o componentes externos.",
  "Uso inadecuado de caché de objetos.",
  "Incompatibilidad o conflictos entre versiones del CLR.",
  "Bugs en la implementación del recolector de basura del entorno de ejecución."
];

const solucionesCLRGarbage = [
  "Optimizar la gestión de memoria en la aplicación.",
  "Identificar y corregir bucles infinitos o recursiones excesivas.",
  "Realizar una mejor administración de objetos y evitar fugas de memoria.",
  "Ajustar la eficiencia en la recolección de basura.",
  "Optimizar y refactorizar el código de la aplicación.",
  "Reducir el uso intensivo de recursos en el proceso de recolección de basura.",
  "Revisar y eliminar referencias fuertes a objetos innecesarios.",
  "Reevaluar y mejorar el uso de objetos estáticos o de larga duración.",
  "Optimizar las estructuras de datos utilizadas.",
  "Administrar adecuadamente los recursos de memoria en múltiples hilos de ejecución.",
  "Liberar correctamente los recursos no administrados.",
  "Reducir la generación de objetos temporales o intermedios.",
  "Evaluar y mejorar el algoritmo de recolección de basura utilizado.",
  "Implementar y utilizar finalizadores de objetos de manera adecuada.",
  "Revisar y gestionar correctamente los pines de memoria.",
  "Garantizar la liberación adecuada de conexiones a recursos externos.",
  "Evaluar y limitar el impacto de extensiones o complementos de terceros.",
  "Optimizar el uso de eventos o suscripciones.",
  "Realizar una compactación adecuada de la memoria.",
  "Monitorizar y ajustar el recolector de basura de forma regular.",
  "Revisar y corregir errores en la gestión de punteros y referencias.",
  "Mitigar la fragmentación de memoria en el sistema.",
  "Gestionar adecuadamente la memoria en bibliotecas o componentes externos.",
  "Optimizar el uso de caché de objetos.",
  "Asegurar la compatibilidad y resolver conflictos entre versiones del CLR.",
  "Corregir errores en la implementación del recolector de basura del entorno de ejecución."
];



        chrome.storage.local.set({ 
                                   causasCPU,
                                   solucionesCPU,
                                   causasBloqueoPOS,
                                   solucionesBloqueoPOS,
                                   causasCargasAltasRAM,
                                   solucionesCargasAltasRAM,
                                   causasBT,
                                   solucionesBT,
                                   causasAlertasAlmacenamiento,
                                   solucionesAlertasAlmacenamiento,
                                   causasProblemasDisponibilidad,
                                   solucionesProblemasDisponibilidad,
                                   causasIndisponibilidadAgente,
                                   solucionesIndisponibilidadAgente,
                                   causasBrokenPipe,
                                   solucionesBrokenPipe,
                                   causasCLRGarbage
                                  });